---
# StatefulSet for pymongo-api
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pymongo-api
  labels:
    app: pymongo-api
spec:
  serviceName: pymongo-api
  replicas: 1
  selector:
    matchLabels:
      app: pymongo-api
  template:
    metadata:
      labels:
        app: pymongo-api
    spec:
      initContainers:
        -   name: wait-for-mongodb-services
            image: bitnami/kubectl:latest
            command: [ 'sh', '-c' ]
            args:
              - |
                echo "Waiting for MongoDB services to be ready..."
                kubectl wait --for=condition=ready pod -l app.kubernetes.io/component=mongos -n mongo --timeout=300s
                echo "MongoDB mongos pods are ready!"
        - name: wait-for-redis
          image: bitnami/kubectl:latest
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for Redis leader pods to be ready..."
              kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=my-redis,role=leader -n redis --timeout=300s
              echo "Redis leader pods are ready!"
              
              echo "Waiting for Redis follower pods to be ready..."
              kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=my-redis,role=follower -n redis --timeout=300s
              echo "Redis follower pods are ready!"
              
              echo "All Redis pods are ready!"
      containers:
      - name: pymongo-api
        image: ghcr.io/felix-neko/pymongo_api:sha-4b5c6ad
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_CLUSTER_MODE
          value: "false"
        - name: REDIS_URL
          value: "redis://10.244.0.38:6379"
        - name: REDIS_PASSWORD
          value: "ZL7YNzIutU"
        - name: MONGODB_DATABASE_NAME
          value: "test_db"
        - name: MONGODB_URL
          value: "mongodb://root:rootpass@mongos-0-nodeport.mongo.svc.cluster.local:27017,mongos-1-nodeport.mongo.svc.cluster.local:27017"
        - name: PORT
          value: "8080"

---
# NodePort service for pymongo-api
apiVersion: v1
kind: Service
metadata:
  name: pymongo-api
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30100
  selector:
    app: pymongo-api
