apiVersion: v1
kind: Service
metadata:
  name: apisix
spec:
  selector:
    app: apisix
  ports:
  - name: http
    port: 9080
    targetPort: 9080
    nodePort: 30080
  - name: admin
    port: 9180
    targetPort: 9180
    nodePort: 30180
  type: NodePort
