name: Docker Image CI

on:
  push:
    branches: [ "main", "sandboxing" ]
  pull_request:
    branches: [ "main", "sandboxing" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image for app.py
      run: docker build api_app --tag pymongo_api:$(date +%s)
